# Generated by Django 5.1.7 on 2025-03-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_is_sale_product_sale_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sale_price",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
